// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4W529baYW6CUtgtQoebIzcB-9Zb4g5l4',
    appId: '1:639288390019:web:0fcd30201cd5d2ed1086b6',
    messagingSenderId: '639288390019',
    projectId: 'match-matter',
    authDomain: 'match-matter.firebaseapp.com',
    storageBucket: 'match-matter.appspot.com',
    measurementId: 'G-ZB4724LQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUWB45H6BrPZC_rusjprLDwcdCxHms4A',
    appId: '1:639288390019:android:9935a668b46df4e81086b6',
    messagingSenderId: '639288390019',
    projectId: 'match-matter',
    storageBucket: 'match-matter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNr6bdt7xMxPhuPYaOYlStDgOQ71aiq8',
    appId: '1:639288390019:ios:1c835edb8e75627a1086b6',
    messagingSenderId: '639288390019',
    projectId: 'match-matter',
    storageBucket: 'match-matter.appspot.com',
    iosBundleId: 'com.example.matchmatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtNr6bdt7xMxPhuPYaOYlStDgOQ71aiq8',
    appId: '1:639288390019:ios:1c835edb8e75627a1086b6',
    messagingSenderId: '639288390019',
    projectId: 'match-matter',
    storageBucket: 'match-matter.appspot.com',
    iosBundleId: 'com.example.matchmatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4W529baYW6CUtgtQoebIzcB-9Zb4g5l4',
    appId: '1:639288390019:web:24f7d142f90033e81086b6',
    messagingSenderId: '639288390019',
    projectId: 'match-matter',
    authDomain: 'match-matter.firebaseapp.com',
    storageBucket: 'match-matter.appspot.com',
    measurementId: 'G-ZEGZWTBKHV',
  );
}
